version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=europea_library
    ports:
      - '5439:5432'
    volumes:
      - db:/var/lib/postgresql/europea_library
volumes:
  db:
    driver: local