spring:
  batch:
    jdbc:
      initialize-schema: always
  mvc:
    dispatch-options-request: true
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:europealibrary.db
    username: admin
    password: password
    testOnBorrow: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        default_schema: public
        generate_statistics: true
        highlight_sql: true
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  liquibase:
    change-log: classpath:/database/db.changelog.xml
    enabled: true
  servlet:
    multipart:
      enabled: false
server:
  port: 8081
com:
  andreidodu:
    europa-library:
      e-books-directory: "/home"

db1:
  url: jdbc:postgresql://localhost:5436/europealibrary
  username: admin
  password: password